name: "Manual Terraform Deployment"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
          - docker-compose-dev
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform-manual:
    name: "Terraform ${{ github.event.inputs.action }} for ${{ github.event.inputs.environment }}"
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment == 'docker-compose-dev' && 'docker-compose' || github.event.inputs.environment }}
    defaults:
      run:
        working-directory: ./terraform
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.7"

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        if: github.event.inputs.environment == 'docker-compose-dev'

      - name: Fly.io Authentication Check
        run: |
          mkdir -p ~/.fly
          echo "${{ secrets.FLY_API_TOKEN }}" > ~/.fly/access_token
          if [[ "${{ github.event.inputs.environment }}" == "docker-compose-dev" ]]; then
            flyctl auth whoami || (echo "Error: Not authenticated with Fly.io" && exit 1)
          fi

      - name: Run Deployment Script
        run: |
          chmod +x deploy.sh
          ./deploy.sh ${{ github.event.inputs.environment }} ${{ github.event.inputs.action }} --env-vars
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} 